name: Playwright Tests & Deploy Report

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history for branch switching

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Deploy Playwright Report to `gh-pages`
        if: always()
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          # Force clean any local changes to avoid conflicts
          git reset --hard
          git clean -fd

          # Ensure `gh-pages` branch exists and checkout
          git fetch origin gh-pages || echo "No gh-pages branch found, creating one..."
          git checkout gh-pages || git checkout --orphan gh-pages

          # Remove old files (clean up previous report)
          rm -rf *

          # Move Playwright report to root
          mv playwright-report/* .

          # Commit and push the latest report
          git add .
          git commit -m "Update Playwright report"
          git push -f origin gh-pages
