name: Playwright Tests & Report Deployment

on:
  push:
    branches:
      - main  # Change if needed
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Ensure Playwright Report Directory Exists
        run: mkdir -p playwright-report

      - name: Copy Playwright Report
        run: |
          mkdir -p temp-playwright-report
          cp -r playwright-report/* temp-playwright-report/
        

      - name: Deploy Playwright Report to GitHub Pages
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages
          rm -rf playwright-report
          mkdir -p playwright-report
          mv temp-playwright-report/* playwright-report/
          git add playwright-report
          git commit -m "Update Playwright report"
          git push origin gh-pages --force
