name: Playwright Tests & Deploy Report

on:
  push:
    branches:
      - main

  workflow_dispatch:  # Enables manual trigger

permissions:
  contents: write  # Grant write permissions to push to gh-pages

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'  # Cache dependencies

      - name: Restore Playwright Browsers Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install Dependencies (if not cached)
        run: npm ci  # Faster install with package-lock.json

      - name: Install Playwright Browsers (if not cached)
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test || echo "tests failed,continuing...."
        continue-on-error: true  # Allow workflow to proceed even if tests fail

      - name: Ensure Playwright Report Exists
        run: mkdir -p playwright-report
        if: always()

   

      - name: Copy Playwright Report to Temporary Directory
        run: |
          mkdir -p temp-playwright-report
          cp -r playwright-report/* temp-playwright-report/
          cp playwright-report/index.html temp-playwright-report/index.html
        if: always()  # Ensures the report is saved even if tests fail

    

      - name: Deploy Playwright Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: temp-playwright-report
          publish_branch: gh-pages
        if: always()
