name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    permissions:
      contents: write  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'  # ✅ Caches npm dependencies automatically

      - name: Restore Playwright Browsers Cache  # ✅ Restores cached browsers if available
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers (Only If Cache Misses)  # ✅ Installs only if cache is missing
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Ensure docs directory exists
        run: mkdir -p docs/playwright
    
      - name: Run Playwright tests
        run: npx playwright test

      # Upload Playwright Report as an artifact
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: docs/playwright/
          retention-days: 5

      # Commit and Push Report to Repository (for GitHub Pages)
      - name: Commit Playwright Report to Repository
        run: |
           git config --global user.name "github-actions"
           git config --global user.email "github-actions@github.com"
           git add docs/
           git commit -m "Update Playwright Report [skip ci]" || echo "No changes to commit"
           git push origin HEAD:main  # ✅ Ensure you're pushing to the correct branch
